-- AlterTable
ALTER TABLE "LiveRoom" ADD COLUMN     "ttsExpressiveness" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "ttsPauseMs" INTEGER NOT NULL DEFAULT 150,
ADD COLUMN     "ttsPitchOffset" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "ttsSpeed" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
