-- AlterTable
ALTER TABLE "AiModel" ADD COLUMN     "avgTokensPerMessage" INTEGER NOT NULL DEFAULT 500,
ADD COLUMN     "inputPricePer1M" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "outputPricePer1M" INTEGER NOT NULL DEFAULT 0;
